name: accident_tracker
description: A new Accident Detector App.
publish_to: none

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_gif: ^0.0.4
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.0
  permission_handler: ^11.3.1
  sign_in_with_apple: ^6.1.2
  package_info_plus: ^8.0.2
  url_launcher: ^6.0.20
  firebase_remote_config: ^5.1.0
  postgres: ^2.4.4
  firebase_messaging: ^15.1.0
  http: ^1.2.2
  connection_notifier: ^2.0.1
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.0.15
  wakelock_plus: ^1.2.8
  fluttertoast: ^8.2.8
  animated_rating_stars: ^1.0.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.0
  firebase_app_check: ^0.3.1+1
  share_plus: ^10.0.2
  tutorial_coach_mark: ^1.2.4
  sentry_flutter: ^8.9.0
  in_app_review: ^2.0.0
  shorebird_code_push: ^1.1.4
  vibration: ^2.0.0
  provider: ^6.1.2
  salomon_bottom_bar: ^3.3.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  responsive_framework: ^1.5.1
  intl: ^0.19.0
  flutter_flavorizr: ^2.2.3
  country_flags: ^3.2.0
  firebase_database: ^11.3.2
  # geolocator: ^13.0.2
  # geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/main.png
  adaptive_icon_background: '#ffffff'
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml

flutter_intl:
  enabled: true

# To add assets to your application, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  ide: "vscode"
  flavors:
    production:
      app:
        name: "Accident Detector"

      android:
        applicationId: "com.example.accident_tracker"

    unit:
      app:
        name: "Accident Detector Units"

      android:
        applicationId: "com.example.accident_tracker.unit"

    staging:
      app:
        name: "Accident Detector Testing"

      android:
        applicationId: "com.example.accident_tracker_stg"
        
    development:
      app:
        name: "Accident Detector Developers"

      android:
        applicationId: "com.example.accident_tracker_dev"
