// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8OHw3JuKU3VEjGgcx2GLSG-Xzb_po35Y',
    appId: '1:584287843034:web:5550d036876e0f2ead2be3',
    messagingSenderId: '584287843034',
    projectId: 'ivision-1a692',
    authDomain: 'ivision-1a692.firebaseapp.com',
    databaseURL: 'https://ivision-1a692-default-rtdb.firebaseio.com',
    storageBucket: 'ivision-1a692.appspot.com',
    measurementId: 'G-TE2CCEBJPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACwVbpFmGfSjHCg9eb6j-nMFhlTJB7z7o',
    appId: '1:584287843034:android:fbe4881bdcb6295aad2be3',
    messagingSenderId: '584287843034',
    projectId: 'ivision-1a692',
    databaseURL: 'https://ivision-1a692-default-rtdb.firebaseio.com',
    storageBucket: 'ivision-1a692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOtpr6uF3Ra8_GKyd_rAMHG55WCz0rtcY',
    appId: '1:584287843034:ios:bc29bcdbf015538bad2be3',
    messagingSenderId: '584287843034',
    projectId: 'ivision-1a692',
    databaseURL: 'https://ivision-1a692-default-rtdb.firebaseio.com',
    storageBucket: 'ivision-1a692.appspot.com',
    iosBundleId: 'com.example.accidentTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOtpr6uF3Ra8_GKyd_rAMHG55WCz0rtcY',
    appId: '1:584287843034:ios:bc29bcdbf015538bad2be3',
    messagingSenderId: '584287843034',
    projectId: 'ivision-1a692',
    databaseURL: 'https://ivision-1a692-default-rtdb.firebaseio.com',
    storageBucket: 'ivision-1a692.appspot.com',
    iosBundleId: 'com.example.accidentTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8OHw3JuKU3VEjGgcx2GLSG-Xzb_po35Y',
    appId: '1:584287843034:web:cd0fdfe10f742637ad2be3',
    messagingSenderId: '584287843034',
    projectId: 'ivision-1a692',
    authDomain: 'ivision-1a692.firebaseapp.com',
    databaseURL: 'https://ivision-1a692-default-rtdb.firebaseio.com',
    storageBucket: 'ivision-1a692.appspot.com',
    measurementId: 'G-P5GYC5YT5G',
  );
}
